environment:
  global:
    RANDOM_SEED: 0
  matrix:
    - PYTHON_MAJOR: 2
      PYTHON_MINOR: 7

cache:
  - .venv -> Makefile

install:
  # Add Make and Python to the PATH
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%;%PATH%
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%\Scripts;%PATH%
  # Install system dependencies
  - pip install pipenv==7.2.8
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make check
  - make test
